local modded_units = {
    {"teb_pikemen", "core"},
    {"teb_montante_greatswords", "special", 2},
    {"teb_republican_guard", "special", 1},
    {"teb_paymaster", "rare", 1},
    {"teb_pavisiers", "core"},
    {"teb_sartosan_pirates", "special", 1},
    {"teb_broken_lances", "core"},
    {"teb_noble_retinue", "rare", 1},
    {"teb_encarmine", "rare", 1},
    {"teb_carabiniers", "special", 1},
    {"teb_light_cannon", "special", 1},
    {"teb_conqui_royal_guard", "special", 1},
    {"teb_conqui_adventurers", "special", 1},
    {"teb_conqui_riders", "special", 1},
    {"teb_conqui_lancers", "core"},
    {"teb_kotrs", "special", 2},
    {"teb_bwatch", "rare", 1},
    {"teb_shieldbearers", "special", 2},
    {"teb_enforcers", "special", 1},
    {"teb_militia_archers", "core"},
    {"teb_freelance_knights", "core"},
    {"teb_militia_knights", "core"},
    {"teb_light_scouts", "core"},
    {"teb_border_rangers", "core"},
    {"teb_swash", "special", 1},
    {"teb_duellists", "core"},
    {"teb_sisters", "rare", 1},
    {"teb_xbow_cav", "special", 1},
    {"teb_irrana", "core"},
    {"teb_half_pikes", "core"},
    {"teb_militia_spearmen", "core"},
    {"teb_billmen", "core"},
    {"teb_billmen_garri", "core"},
    {"teb_guard_kossars", "special", 1},
    {"teb_xbowmen", "core"},
    {"teb_handgunners", "core"},
    {"teb_galloper_limbered", "rare", 2},
    {"teb_galloper", "rare", 2},
    {"teb_tank", "rare", 3},
    {"teb_roc_dieterfist", "special", 1},
    {"teb_roc_estragon", "special", 1},
    {"teb_roc_verena", "core"},
    {"teb_roc_strygos", "core"},
    {"teb_roc_broswords", "core"},
    {"teb_roc_gwatch", "rare", 1},
    {"teb_roc_kotss", "special", 2},
    {"teb_roc_organ", "rare", 2},
    {"teb_roc_gunn", "core"},
    {"teb_roc_montecastello", "rare", 1},
    {"teb_tank_ror", "rare", 3},
    {"teb_ricco", "core"},
    {"teb_alcatani", "core"},
    {"teb_pirazzo", "core"},
    {"teb_pirazzo_xbows", "core"},
    {"teb_leopard", "core"},
    {"teb_venators", "special", 2},
    {"teb_vespero", "core"},
    {"teb_marksmen", "core"},
    {"teb_besiegers", "core"},
    {"teb_muktar", "rare", 1},
    {"teb_amazons", "rare", 1},
    {"teb_cursed", "special", 1},
    {"teb_origo", "rare", 1},
    {"teb_manflayers", "rare", 2},
    {"teb_asarnil", "rare", 3},
    {"teb_tichi", "rare", 2},
    {"teb_bronzino_limbered", "rare", 2},
    {"teb_bronzino", "rare", 2},
    {"teb_birdmen", "rare", 1},
    {"teb_golden_lion", "rare", 2}
}


local ttc = core:get_static_object("tabletopcaps")
if ttc then
    ttc.add_setup_callback(function()
        ttc.add_unit_list(modded_units)
    end)
end