<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\PackFiles\Shared.PackFiles.Core\Shared.PackFiles.Core.csproj" />
    <ProjectReference Include="..\..\..\Shared\Logging\Shared.Core.Logging\Shared.CoreLog.csproj" />
    <ProjectReference Include="..\..\..\Shared\GameFiles\Shared.GameFormats.csproj" />
  </ItemGroup>

</Project>
